find_path(Z3_INCLUDE_DIR NAMES z3.h)
find_library(Z3_LIBRARIES NAMES z3)

message(STATUS "Z3: ${Z3_INCLUDE_DIR} ${Z3_LIBRARIES}")

include(CMakePushCheckState)
include(CheckSymbolExists)
include(CheckFunctionExists)

cmake_push_check_state(RESET)
message(STATUS "Looking for Z3_get_estimated_alloc_size")
set(CMAKE_REQUIRED_INCLUDES "${Z3_INCLUDE_DIR}")
CHECK_SYMBOL_EXISTS(Z3_get_estimated_alloc_size z3.h Z3_HAVE_GET_ESTIMATED_ALLOC_SIZE)
cmake_reset_check_state()
if(Z3_HAVE_GET_ESTIMATED_ALLOC_SIZE)
  set(CMAKE_REQUIRED_LIBRARIES "${Z3_LIBRARIES}")
  CHECK_FUNCTION_EXISTS(Z3_get_estimated_alloc_size z3.h Z3_HAVE_GET_ESTIMATED_ALLOC_SIZE)
endif()
cmake_pop_check_state()
if(Z3_HAVE_GET_ESTIMATED_ALLOC_SIZE)
  message(STATUS "Looking for Z3_get_estimated_alloc_size: found")
  set(Z3_HAVE_GET_ESTIMATED_ALLOC_SIZE "-DZ3_HAVE_GET_ESTIMATED_ALLOC_SIZE")
else()
  message(STATUS "Looking for Z3_get_estimated_alloc_size: not found")
endif()
